urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = "pyusite"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("pyusite:homepage"))),
    path("homepage/", views.home_page, name="homepage"),
    path("page/", views.PageList.as_view(), name="page-list"),
    path("page/edit/create/", views.PageCreate.as_view(), name="page-create"),
    path("page/edit/update/<int:pk>/", views.PageUpdate.as_view(), name="page-update"),
    path("page/edit/delete/<int:pk>/", views.PageDelete.as_view(), name="page-delete"),
    path("page/edit/detail/<int:pk>/", views.PageDetail.as_view(), name="page-detail"),
    path("page/edit/popup/", views.PageCreate.as_view(), name="page-popup"),
    path(
        "page/<int:pk>/",
        views.PageView.as_view(),
        name="page",
    ),
    path(
        "page/<slug:slug>/",
        views.PageView.as_view(),
        name="page",
    ),
    path("section/", views.SectionList.as_view(), name="section-list"),
    path("section/edit/create/", views.SectionCreate.as_view(), name="section-create"),
    path(
        "section/edit/update/<int:pk>/",
        views.SectionUpdate.as_view(),
        name="section-update",
    ),
    path(
        "section/edit/delete/<int:pk>/",
        views.SectionDelete.as_view(),
        name="section-delete",
    ),
    path(
        "section/edit/detail/<int:pk>/",
        views.SectionDetail.as_view(),
        name="section-detail",
    ),
    path("section/edit/popup/", views.SectionCreate.as_view(), name="section-popup"),
    path("rack/", views.RackList.as_view(), name="rack-list"),
    path(
        "rack/<int:pk>/",
        views.RackView.as_view(),
        name="rack",
    ),
    path(
        "rack/<slug:slug>/",
        views.RackView.as_view(),
        name="rack",
    ),
    path("rack/edit/create/", views.RackCreate.as_view(), name="rack-create"),
    path("rack/edit/update/<int:pk>/", views.RackUpdate.as_view(), name="rack-update"),
    path("rack/edit/delete/<int:pk>/", views.RackDelete.as_view(), name="rack-delete"),
    path("rack/edit/detail/<int:pk>/", views.RackDetail.as_view(), name="rack-detail"),
    path("rack/edit/popup/", views.RackCreate.as_view(), name="rack-popup"),
    path("article/", views.ArticleList.as_view(), name="article-list"),
    path(
        "article/<int:pk>/",
        views.ArticleView.as_view(),
        name="article",
    ),
    path(
        "article/<slug:slug>/",
        views.ArticleView.as_view(),
        name="article",
    ),
    path("article/edit/create/", views.ArticleCreate.as_view(), name="article-create"),
    path(
        "article/edit/update/<int:pk>/",
        views.ArticleUpdate.as_view(),
        name="article-update",
    ),
    path(
        "article/edit/delete/<int:pk>/",
        views.ArticleDelete.as_view(),
        name="article-delete",
    ),
    path(
        "article/edit/detail/<int:pk>/",
        views.ArticleDetail.as_view(),
        name="article-detail",
    ),
    path("article/edit/popup/", views.ArticleCreate.as_view(), name="article-popup"),
    path("image/edit/popup/", views.ImijCreate.as_view(), name="imij-popup"),
    path("image/<int:pk>/", views.ImijDetail.as_view(), name="imij-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pyusite/default/_base.html
{% extends 'touglates/base.html' %}
{% load static %}
{% load touglates_tags %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'pyusite/default/pyusite.css' %}">
{% endblock %}
{% block body %}
<body>

  {% if "UPPER_BANNER_IMAGE" in pyusite and pyusite.UPPER_BANNER_IMAGE %}
  <div id="upperhead" class="head" {% if "UPPER_HEAD_STYLE" in pyusite %} style="{{ pyusite.UPPER_HEAD_STYLE }}"{% endif %}>
    <img src="{{ pyusite.UPPER_BANNER_IMAGE }}" alt="{{ pyusite.UPPER_BANNER_IMAGE_ALT }}" class="UPPER_BANNER" {% if 'UPPER_BANNER_IMAGE_STYLE' in pyusite %} style="{{ pyusite.UPPER_BANNER_IMAGE_STYLE }}" {% endif %} />
  </div>
  {% endif %}
  <div id="head" class="head">
      <a href="{% url 'pyusite:homepage' %}">
          {% if pyusite.BANNER_IMAGE %}
              <img src="{{ pyusite.BANNER_IMAGE }}" alt="{{ pyusite.BANNER_IMAGE_ALT }}" class="banner" {% if 'BANNER_IMAGE_STYLE' in pyusite %} style="{{ pyusite.BANNER_IMAGE_STYLE }}" {% endif %} />
          {% endif %}
          {% if pyusite.BANNER_TEXT %}
              <div id="bannertext">
                  {{ pyusite.BANNER_TEXT }}
              </div>
          {% endif %}
      </a>
  </div>

  {% if messages %}
      <div id="messages">
          {% for message in messages %}
              {{ message }}
          {% endfor %}
      </div>
  {% endif %}

  {% for menu in main_menus %}
      {% if forloop.first %}
      <div id="sitemenu">
          {% for item in menu.menuitem_set.all %}
              <a href="{{ base_url }}{{ item.href }}">{{ item.label }}</a>
          {% endfor %}
      </div>
      {% endif %}
  {% endfor %}

  <div id="mainstage">
      {% block content %}
      {% endblock %}
  </div>

  <div id="footer">
      <div>
      {{ pyusite.FOOTER_CONTENT|safe }}
      </div>
      <div>
          {% if user.is_authenticated %}
          <form method="POST" class="menu-item" action="{% url 'logout' %}?next={{ request.path }}">{% csrf_token %}<button type="submit" class="menu-item">Log Out</button></form>
          {% else %}
          <a href="{% url 'login' %}?next={{ request.path }}">Log in</a>
          {% endif %}
      </div>
  </div>
  <script>

var sitemenuHeight = 0
var sitemenu = document.getElementById("sitemenu")
if( sitemenu != null) {
sitemenuHeight = sitemenu.offsetHeight
var sitemenuStartingTop = sitemenu.offsetTop
var sitemenuStartingPosition = sitemenu.style.position
}
var upperheadHeight = 0
var upperhead = document.getElementById("upperhead")
if(upperhead != null) {
upperheadHeight = upperhead.offsetHeight
}
var headHeight = document.getElementById("head").offsetHeight

if (sitemenu != null) {

if(window.innerWidth < 600 ) {
var menuItem = document.getElementById("sitemenu").firstElementChild
if(menuItem != null) {
sitemenuItemStyleDisplay = menuItem.style.display
var menuItemHide = menuItem.cloneNode()
menuItemHide.innerText = "^"
menuItemHide.href="#"
menuItemHide.id = "menuItemHide"
menuItemHide.addEventListener('click', function(e) {
  e.preventDefault()
  hidesitemenu()
});
}
sitemenu.appendChild(menuItemHide)
}
}
function scroll_effects(e) {

if( sitemenu != null ) {
if(window.scrollY > sitemenuStartingTop) {
sitemenu.style.position="sticky"
sitemenu.style.top="0"
} else {
sitemenu.style.position = sitemenuStartingPosition
}
}
if (upperhead != null) {
if(window.scrollY > (upperheadHeight - sitemenuHeight ) ) {
upperhead.style.top = ( 0 - ( window.scrollY - ( upperheadHeight - sitemenuHeight ) ) ) + "px"
}
}
}
function hidesitemenu () {
menuItems = document.querySelectorAll("#sitemenu a")
for(menuItem of menuItems) {
if(menuItem.id == "menuItemHide") {
if(menuItem.innerText == "^") {
  menuItem.innerText = '\u{2304}'
} else {
  menuItem.innerText = "^"
}
} else {
if(menuItem.style.display == "none") {
  menuItem.style.display = sitemenuItemStyleDisplay
} else {
  menuItem.style.display = "none"
}
}
}
}


window.addEventListener("scroll", function(e) {
scroll_effects(e);
})



  </script>
</body>
{% endblock %}


{% comment %}
<!--
<html>
    <head>
      {% if object %}
        <meta property="og:title" content="{{ object.title|safe  }}" />
        {% if object.featured_image %}
            <meta property="og:image" content="{{ object.featured_image.imagefile.url  }}" />
            <meta property="og:image:alt" content="{{ object.featured_image.alt_text  }}" />
        {% endif %}
      {% else %}
          {% if 'keyed_head_lines' in pyusite %}
              {% if 'og_image' in pyusite.keyed_head_lines %}
                  {{ pyusite.keyed_head_lines.og_image|safe  }}
              {% endif %}
              {% if 'og_image_alt' in pyusite.keyed_head_lines %}
                  {{ pyusite.keyed_head_lines.og_image_alt|safe  }}
              {% endif %}
          {% endif %}
      {% endif %}


        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
          {% if object.title %}{{ object.title | safe }}: {% endif %}{{ pyusite.SITE_NAME }}
        </title>
        <link rel="stylesheet" href="{% static pyusite.STATIC_DIR|add:'/pyusite.css' %}">
        {% if pyusite.COLORSCHEME %}
          <link rel="stylesheet" href="{% static pyusite.STATIC_DIR|add:'/'|add:pyusite.COLORSCHEME|add:'.css' %}">
        {% endif %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Gilda+Display&display=swap" rel="stylesheet">
        {% for head_line in pyusite.head_lines %}
            {{ head_line|safe }}
        {% endfor %}
        {% for head_line in pyusite.head_lines_replaceable %}
            {{ head_line|safe }}
        {% endfor %}
        <script src="{% static 'touglates/touglates.js' %}"></script>
    </head>
    <body>

        {% if "UPPER_BANNER_IMAGE" in pyusite and pyusite.UPPER_BANNER_IMAGE %}
        <div id="upperhead" class="head" {% if "UPPER_HEAD_STYLE" in pyusite %} style="{{ pyusite.UPPER_HEAD_STYLE }}"{% endif %}>
          <img src="{{ pyusite.UPPER_BANNER_IMAGE }}" alt="{{ pyusite.UPPER_BANNER_IMAGE_ALT }}" class="UPPER_BANNER" {% if 'UPPER_BANNER_IMAGE_STYLE' in pyusite %} style="{{ pyusite.UPPER_BANNER_IMAGE_STYLE }}" {% endif %} />
        </div>
        {% endif %}
        <div id="head" class="head">
            <a href="{% url 'pyusite:homepage' %}">
                {% if pyusite.BANNER_IMAGE %}
                    <img src="{{ pyusite.BANNER_IMAGE }}" alt="{{ pyusite.BANNER_IMAGE_ALT }}" class="banner" {% if 'BANNER_IMAGE_STYLE' in pyusite %} style="{{ pyusite.BANNER_IMAGE_STYLE }}" {% endif %} />
                {% endif %}
                {% if pyusite.BANNER_TEXT %}
                    <div id="bannertext">
                        {{ pyusite.BANNER_TEXT }}
                    </div>
                {% endif %}
            </a>
        </div>

        {% if messages %}
            <div id="messages">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        {% for menu in main_menus %}
            {% if forloop.first %}
            <div id="sitemenu">
                {% for item in menu.menuitem_set.all %}
                    <a href="{{ base_url }}{{ item.href }}">{{ item.label }}</a>
                {% endfor %}
            </div>
            {% endif %}
        {% endfor %}

        <div id="mainstage">
            {% block content %}
            {% endblock %}
        </div>

        <div id="footer">
            <div>
            {{ pyusite.FOOTER_CONTENT|safe }}
            </div>
            <div>
                {% if user.is_authenticated %}
                <form method="POST" class="menu-item" action="{% url 'logout' %}?next={{ request.path }}">{% csrf_token %}<button type="submit" class="menu-item">Log Out</button></form>
                {% else %}
                <a href="{% url 'login' %}?next={{ request.path }}">Log in</a>
                {% endif %}
            </div>
        </div>
        <script>

var sitemenuHeight = 0
var sitemenu = document.getElementById("sitemenu")
if( sitemenu != null) {
	sitemenuHeight = sitemenu.offsetHeight
	var sitemenuStartingTop = sitemenu.offsetTop
	var sitemenuStartingPosition = sitemenu.style.position
}
var upperheadHeight = 0
var upperhead = document.getElementById("upperhead")
if(upperhead != null) {
	upperheadHeight = upperhead.offsetHeight
}
var headHeight = document.getElementById("head").offsetHeight

if (sitemenu != null) {

	if(window.innerWidth < 600 ) {
		var menuItem = document.getElementById("sitemenu").firstElementChild
		if(menuItem != null) {
			sitemenuItemStyleDisplay = menuItem.style.display
			var menuItemHide = menuItem.cloneNode()
			menuItemHide.innerText = "^"
			menuItemHide.href="#"
			menuItemHide.id = "menuItemHide"
			menuItemHide.addEventListener('click', function(e) {
				e.preventDefault()
				hidesitemenu()
			});
		}
		sitemenu.appendChild(menuItemHide)
	}
}
function scroll_effects(e) {

	if( sitemenu != null ) {
		if(window.scrollY > sitemenuStartingTop) {
			sitemenu.style.position="sticky"
			sitemenu.style.top="0"
		} else {
			sitemenu.style.position = sitemenuStartingPosition
		}
	}
	if (upperhead != null) {
		if(window.scrollY > (upperheadHeight - sitemenuHeight ) ) {
  		upperhead.style.top = ( 0 - ( window.scrollY - ( upperheadHeight - sitemenuHeight ) ) ) + "px"
		}
	}
}
function hidesitemenu () {
	menuItems = document.querySelectorAll("#sitemenu a")
	for(menuItem of menuItems) {
		if(menuItem.id == "menuItemHide") {
			if(menuItem.innerText == "^") {
				menuItem.innerText = '\u{2304}'
			} else {
				menuItem.innerText = "^"
			}
		} else {
			if(menuItem.style.display == "none") {
				menuItem.style.display = sitemenuItemStyleDisplay
			} else {
				menuItem.style.display = "none"
			}
		}
	}
}


window.addEventListener("scroll", function(e) {
  scroll_effects(e);
})



        </script>
    </body>
</html>
  -->
{% endcomment %}

templates/pyusite/default/article.html
{% extends './_base.html'%}
{% load touglates_tags %}
{% load pyusite_extras %}
{% block content %}
<div id="mainsection">
  <div class="article" id="object_{{ object.pk }}">
    {% if article.title and article.show_title %}
      <h2>{{ object.title }}</h2>
    {% endif %}
    <div class="article_content {{ object.content_classes }}" >
      {% if object.author.is_staff  %}
        {{ object.content|safe }}
      {% else %}
        {{ object.content }}
      {% endif %}
      {% if object.iframe_document %}
        <iframe src="{{ object.iframe_document.doc_file.url }}"{% if object.iframe_height %} height="{{ object.iframe_height }}"{% endif %} style="width:90%">"Loading.."</iframe>
      {% elif object.iframe_src %}
        <iframe src="{{ object.iframe_src }}"{% if object.iframe_height %} height="{{ object.iframe_height }}"{% endif %} style="width:90%">"Loading.."</iframe>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

templates/pyusite/default/page.html
{% extends './_base.html'%}
{% load touglates_tags %}
{% load pyusite_extras %}
{% block content %}
  {% for section in special_sections %}
    {% if section.slug == "left-sidebar" %}
      <div id="div_left-sidebar" class="sidebar">
        {% if section.title and section.show_title %}
          <h2>{{ section.title }}</h2>
        {% endif %}
        {% if section.content_before_racks %}
          <div class="secfion_content">
            {{ section.content_before_racks|safe }}
          </div>
        {% endif %}
        <div class="racks">
          {% for rack in section.racks %}
            <div class="rack-wrapper" data-width="{{ rack.width }}">
              <div class="rack" id="rack_{{ rack.pk }}">
                {% if rack.title and rack.show_title %}
                  <h3>{{ rack.title }}</h3>
                {% endif %}
                {% if rack.content_before_articles %}
                  <div class="rack-content">
                    {{ rack.content_before_articles|safe }}
                  </div>
                {% endif %}
                {% for hanger in rack.hangers %}
                  <div class="article" id="hanger.article_{{ article.pk }}">
                    {% if hanger.article.summary %}
                      {% if hanger.article.title and hanger.article.show_title %}
                        <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                      {% endif %}
                      <div class="{{ hanger.article.content_classes }}" >
                        {% if hanger.article.author.is_staff  %}
                          {{ hanger.article.summary|safe }}
                        {% else %}
                          {{ hanger.article.summary }}
                        {% endif %}
                        {% if hanger.article.read_more %}
                          <div class="readmore"><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.read_more }}</a></div>
                        {% endif %}
                      </div>
                    {% else %}
                      {% if hanger.article.title and hanger.article.show_title %}
                        <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                      {% endif %}
                      <div class="{{ hanger.article.content_classes }}" >
                        {% if hanger.article.if_summary_blank == 1 %}
                          {% if hanger.article.author.is_staff  %}
                            {{ hanger.article.content|safe }}
                          {% else %}
                            {{ hanger.article.content }}
                          {% endif %}
                          {% if hanger.article.iframe_document %}
                            <iframe src="{{ hanger.article.iframe_document.doc_file.url }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                          {% elif hanger.article.iframe_src %}
                            <iframe src="{{ hanger.article.iframe_src }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                          {% endif %}
                        {% endif %}
                      </div>
                    {% endif %}
                  </div>
                {% endfor %}
                {% if rack.content_after_articles %}
                  <div class="rack-content">
                    {{ rack.content_after_articles|safe }}
                  </div>
                {% endif %}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endfor %}
  <div id="mainsection">
    {% for section in sections %}
      <div class="section">
        {% if section.title and section.show_title %}
          <h2>{{ section.title }}</h2>
        {% endif %}
        {% if section.content_before_racks %}
          <div class="secfion_content">
            {{ section.content_before_racks|safe }}
          </div>
        {% endif %}
        <div class="racks">
          {% for rack in section.racks %}
            {% if rack.hangers|length > 0 %}
              <div class="rack-wrapper" data-width="{{ rack.width }}">
                <div class="rack" id="rack_{{ rack.pk }}">
                  {% if rack.title and rack.show_title %}
                    <h3>{{ rack.title }}</h3>
                  {% endif %}
                  {% if rack.content_before_articles %}
                    <div class="rack-content">
                      {{ rack.content_before_articles|safe }}
                    </div>
                  {% endif %}
                  {% for hanger in rack.hangers %}
                    <div class="article" id="hanger.article_{{ article.pk }}">
                      {% if hanger.article.summary %}
                        {% if hanger.article.title and hanger.article.show_title %}
                          <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                        {% endif %}
                        <div class="{{ hanger.article.content_classes }}" >
                          {% if hanger.article.author.is_staff  %}
                            {{ hanger.article.summary|safe }}
                          {% else %}
                            {{ hanger.article.summary }}
                          {% endif %}
                          {% if hanger.article.read_more %}
                            <div class="readmore"><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.read_more }}</a></div>
                          {% endif %}
                        </div>
                      {% else %}
                        {% if hanger.article.title and hanger.article.show_title %}
                          <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                        {% endif %}
                        <div class="{{ hanger.article.content_classes }}" >
                          {% if hanger.article.if_summary_blank == 1 %}
                            {% if hanger.article.author.is_staff  %}
                              {{ hanger.article.content|safe }}
                            {% else %}
                              {{ hanger.article.content }}
                            {% endif %}
                            {% if hanger.article.iframe_document %}
                              <iframe src="{{ hanger.article.iframe_document.doc_file.url }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                            {% elif hanger.article.iframe_src %}
                              <iframe src="{{ hanger.article.iframe_src }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                            {% endif %}
                          {% endif %}
                        </div>
                      {% endif %}
                    </div>
                  {% endfor %}
                  {% if rack.content_after_articles %}
                    <div class="rack-content">
                      {{ rack.content_after_articles|safe }}
                    </div>
                  {% endif %}
                </div>
              </div>
            {% endif %}
          {% endfor %}
        </div>
        {% if section.content_after_racks %}
          <div class="section_content">
            {{ section.content_after_racks|safe }}
          </div>
        {% endif %}
      </div>
  {% endfor %}
  </div>
  {% for section in special_sections %}
    {% if section.slug == "right-sidebar" %}
      <div id="div_right-sidebar" class="sidebar">
        {% if section.title and section.show_title %}
          <h2>{{ section.title }}</h2>
        {% endif %}
        {% if section.content_before_racks %}
          <div class="secfion_content">
            {{ section.content_before_racks|safe }}
          </div>
        {% endif %}
        <div class="racks">
          {% for rack in section.racks %}
            <div class="rack-wrapper" data-width="{{ rack.width }}">
              <div class="rack" id="rack_{{ rack.pk }}">
                {% if rack.title and rack.show_title %}
                  <h3>{{ rack.title }}</h3>
                {% endif %}
                {% if rack.content_before_articles %}
                  <div class="rack-content">
                    {{ rack.content_before_articles|safe }}
                  </div>
                {% endif %}
                {% for hanger in rack.hangers %}
                  <div class="article" id="hanger.article_{{ article.pk }}">
                    {% if hanger.article.summary %}
                      {% if hanger.article.title and hanger.article.show_title %}
                        <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                      {% endif %}
                      <div class="{{ hanger.article.content_classes }}" >
                        {% if hanger.article.author.is_staff  %}
                          {{ hanger.article.summary|safe }}
                        {% else %}
                          {{ hanger.article.summary }}
                        {% endif %}
                        {% if hanger.article.read_more %}
                          <div class="readmore"><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.read_more }}</a></div>
                        {% endif %}
                      </div>
                    {% else %}
                      {% if hanger.article.title and hanger.article.show_title %}
                        <h3><a href="{% url 'pyusite:article' hanger.article.pk %}">{{ hanger.article.title }}</a></h3>
                      {% endif %}
                      <div class="{{ hanger.article.content_classes }}" >
                        {% if hanger.article.if_summary_blank == 1 %}
                          {% if hanger.article.author.is_staff  %}
                            {{ hanger.article.content|safe }}
                          {% else %}
                            {{ hanger.article.content }}
                          {% endif %}
                          {% if hanger.article.iframe_document %}
                            <iframe src="{{ hanger.article.iframe_document.doc_file.url }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                          {% elif hanger.article.iframe_src %}
                            <iframe src="{{ hanger.article.iframe_src }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                          {% endif %}
                        {% endif %}
                      </div>
                    {% endif %}
                  </div>
                {% endfor %}
                {% if rack.content_after_articles %}
                  <div class="rack-content">
                    {{ rack.content_after_articles|safe }}
                  </div>
                {% endif %}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endfor %}

          <script>
            function resizeRacks() {
              if(window.innerWidth > 600) {
                var sections = document.getElementsByClassName("section")
                for(var section of sections) {
                  var racks = section.getElementsByClassName("rack-wrapper")
                  var total_widths = 0
                  for(var rack of racks) {
                    total_widths += parseInt(rack.dataset["width"])
                  }
                  for(var rack of racks) {
                    rack.style.width = (( 80/total_widths) * rack.dataset["width"] ) + "%"
                  }
                }
              } else {
                var racks = document.getElementsByClassName("rack-wrapper")
                for(var rack of racks) {
                  rack.style.width="90%"
                }
              }
            }
            resizeRacks()
            window.addEventListener("resize", resizeRacks);
          </script>

{% endblock %}

templates/pyusite/default/rack.html
{% extends './_base.html'%}
{% load touglates_tags %}
{% load pyusite_extras %}
{% block content %}
        <div class="rack-wrapper" data-width="{{ rack.width }}">
          <div class="rack" id="rack_{{ rack.pk }}">
            {% if rack.content_before_articles %}
              <div class="rack-content">
                {{ rack.content_before_articles|safe }}
              </div>
            {% endif %}
            {% for hanger in rack.hanger_set.all %}
              <div class="article" id="hanger.article_{{ article.pk }}">
                <h3>{{ hanger.article.title }}</h3>
                <div class="{{ hanger.article.content_classes }}" >
                  {% if hanger.article.author.is_staff  %}
                    {{ hanger.article.content|safe }}
                  {% else %}
                    {{ hanger.article.content }}
                  {% endif %}
                  {% if hanger.article.iframe_document %}
                    <iframe src="{{ hanger.article.iframe_document.doc_file.url }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                  {% elif hanger.article.iframe_src %}
                    <iframe src="{{ hanger.article.iframe_src }}"{% if hanger.article.iframe_height %} height="{{ hanger.article.iframe_height }}"{% endif %}>"Loading.."</iframe>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            {% if rack.content_below_articles %}
              <div class="rack-content">
                {{ rack.content_below_articles|safe }}
              </div>
            {% endif %}
          </div>
        </div>



{% endblock %}