urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = "pyusite"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("pyusite:homepage"))),
    path("homepage/", views.home_page, name="homepage"),
    path("page/", views.PageList.as_view(), name="page-list"),
    path("page/edit/create/", views.PageCreate.as_view(), name="page-create"),
    path("page/edit/update/<int:pk>/", views.PageUpdate.as_view(), name="page-update"),
    path("page/edit/delete/<int:pk>/", views.PageDelete.as_view(), name="page-delete"),
    path("page/edit/detail/<int:pk>/", views.PageDetail.as_view(), name="page-detail"),
    path("page/edit/popup/", views.PageCreate.as_view(), name="page-popup"),
    path(
        "page/<int:pk>/",
        views.PageView.as_view(),
        name="page",
    ),
    path(
        "page/<slug:slug>/",
        views.PageView.as_view(),
        name="page",
    ),
    path("section/", views.SectionList.as_view(), name="section-list"),
    path("section/edit/create/", views.SectionCreate.as_view(), name="section-create"),
    path(
        "section/edit/update/<int:pk>/",
        views.SectionUpdate.as_view(),
        name="section-update",
    ),
    path(
        "section/edit/delete/<int:pk>/",
        views.SectionDelete.as_view(),
        name="section-delete",
    ),
    path(
        "section/edit/detail/<int:pk>/",
        views.SectionDetail.as_view(),
        name="section-detail",
    ),
    path("section/edit/popup/", views.SectionCreate.as_view(), name="section-popup"),
    path("rack/", views.RackList.as_view(), name="rack-list"),
    path(
        "rack/<int:pk>/",
        views.RackView.as_view(),
        name="rack",
    ),
    path(
        "rack/<slug:slug>/",
        views.RackView.as_view(),
        name="rack",
    ),
    path("rack/edit/create/", views.RackCreate.as_view(), name="rack-create"),
    path("rack/edit/update/<int:pk>/", views.RackUpdate.as_view(), name="rack-update"),
    path("rack/edit/delete/<int:pk>/", views.RackDelete.as_view(), name="rack-delete"),
    path("rack/edit/detail/<int:pk>/", views.RackDetail.as_view(), name="rack-detail"),
    path("rack/edit/popup/", views.RackCreate.as_view(), name="rack-popup"),
    path("article/", views.ArticleList.as_view(), name="article-list"),
    path(
        "article/<int:pk>/",
        views.ArticleView.as_view(),
        name="article",
    ),
    path(
        "article/<slug:slug>/",
        views.ArticleView.as_view(),
        name="article",
    ),
    path("article/edit/create/", views.ArticleCreate.as_view(), name="article-create"),
    path(
        "article/edit/update/<int:pk>/",
        views.ArticleUpdate.as_view(),
        name="article-update",
    ),
    path(
        "article/edit/delete/<int:pk>/",
        views.ArticleDelete.as_view(),
        name="article-delete",
    ),
    path(
        "article/edit/detail/<int:pk>/",
        views.ArticleDetail.as_view(),
        name="article-detail",
    ),
    path("article/edit/popup/", views.ArticleCreate.as_view(), name="article-popup"),
    path("image/edit/popup/", views.ImijCreate.as_view(), name="imij-popup"),
    path("image/<int:pk>/", views.ImijDetail.as_view(), name="imij-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from datetime import date
from django.db import models
from django.conf import settings
from django.utils.text import slugify

class Page(models.Model):
    title = models.CharField(
        "title",
        blank=True,
        max_length=200,
        help_text="The title of the page. to be displayed (can be blank)",
    )
    show_title = models.BooleanField(
        "show title",
        default=True,
        help_text="If the title should be shown (if not blank)",
    )
    slug = models.SlugField(
        "name/slug",
        max_length=100,
        unique=True,
        help_text="The name or slug for use in URLs and within the application.  Note: Auto-generated value may not be unique. Uniquness and format are checked after submit",
    )

    is_home = models.BooleanField(
        "is home page", default=False, help_text="If this is the home page"
    )
    order = models.IntegerField(
        "order",
        default=0,
        help_text="The order that the page would appear in a list",
    )
    display = models.CharField(
        "display",
        max_length=2,
        choices=[("Y", "Normal"), ("H", "Hide from Menus"), ("N", "Do not display")],
        default="Y",
        help_text="How the page should be displayed",
    )

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ("order", "title")


class Section(models.Model):
    page = models.ForeignKey(
        Page,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="The page to which this section belongs",
    )
    title = models.CharField(
        "title",
        blank=True,
        max_length=200,
        help_text="The title of the page. to be displayed (can be blank)",
    )
    show_title = models.BooleanField(
        "show title",
        default=True,
        help_text="If the title of this section should be shown (if not blank)",
    )
    slug = models.SlugField(
        "name/slug",
        max_length=100,
        unique=True,
        help_text="The name or slug for use in URLs and within the application.  Note: Auto-generated value may not be unique. Uniquness and format are checked after submit",
    )
    order = models.IntegerField(
        "order",
        default=0,
        help_text="The order that the section should appear on the page",
    )
    content_before_racks = models.TextField(
        blank=True,
        help_text="content to be displayed before the racks",
    )
    content_after_racks = models.TextField(
        blank=True,
        help_text="content to be displayed after the racks",
    )
    display = models.CharField(
        "display when",
        max_length=2,
        choices=[("Y", "Normal"), ("P", "Preview Only"), ("N", "Do not display")],
        default="Y",
        help_text="How the section should be displayed",
    )
    collapse = models.BooleanField(
        "collapse", default=True, help_text="Collapse if there are no racks"
    )
    is_special = models.BooleanField(
        default=False,
        help_text="If the section is special and thus won't be included in the regular loop"
    )
    def __str__(self):
        return '"{}" on page "{}"'.format(
            self.title if self.title > "" else self.slug, self.page
        )

    class Meta:
        ordering = ("page", "order")


class Rack(models.Model):
    section = models.ForeignKey(
        Section,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The section to which the rack belongs",
    )
    title = models.CharField(
        "title",
        blank=True,
        max_length=200,
        help_text="The title of the rack to be displayed (can be blank)",
    )
    show_title = models.BooleanField(
        "show title",
        default=False,
        help_text="If the title should be shown (if not blank)",
    )
    slug = models.SlugField(
        "name/slug",
        max_length=100,
        unique=True,
        help_text="The name or slug for use in URLs and within the application.  Note: Auto-generated value may not be unique. Uniquness and format are checked after submit",
    )
    width = models.IntegerField(
        "width",
        default=1,
        help_text="The width of the rack in multiples of how big it is compared to the narrowest rack",
    )
    show_article_meta = models.CharField(
        "show article meta",
        max_length=2,
        choices=[
            ("00", "None"),
            ("a0", "Author"),
            ("0d", "Publish Date"),
            ("ad", "Author and Date"),
        ],
        default="00",
        help_text="What article meta information should be shown for aticles in racks",
    )
    content_before_articles = models.CharField(
        "content before articles",
        max_length=255,
        blank=True,
        help_text="The content of the rack before any included articles",
    )

    content_after_articles = models.CharField(
        "content after articles",
        max_length=255,
        blank=True,
        help_text="The content of the rack after any included articles",
    )
    order = models.IntegerField(
        "order",
        default=0,
        help_text="A number used for ordering of the rack in a section",
    )
    display = models.CharField(
        "display",
        max_length=2,
        choices=[
            ("Y", "Normal"),
            ("P", "Preview Only"),
            ("N", "Do not display"),
        ],
        default="Y",
        help_text="How the rack should be displayed. Racks that are hidden from sections may still be displayed independently",
    )
    collapse = models.BooleanField(
        "collapse", default=True, help_text="Collapse if there are no hangers/articles"
    )

    def __str__(self):

        return '"{}" in section "{}"'.format(
            self.title if self.title > "" else self.slug, self.section
        )

    class Meta:
        ordering = (
            "section",
            "order",
        )


class Document(models.Model):
    title = models.CharField(
        "title",
        max_length=200,
        blank=True,
        help_text="The title to be displayed with document.  It may or may not correspond to anything in the document itself. (can be blank)",
    )
    show_title = models.BooleanField(
        "show title",
        default=True,
        help_text="If the title should be shown (if not blank)",
    )
    slug = models.SlugField(
        "name/slug",
        max_length=100,
        unique=True,
        help_text="The name or slug for use in URLs and within the application.  Note: Auto-generated value may not be unique. Uniquness and format are checked after submit",
    )

    doc_file = models.FileField(
        upload_to="documents", help_text="The file to be uploaded"
    )

    def __str__(self):
        return (
            self.title
            if self.title > ""
            else self.slug if self.slug > "" else str(self.pk)
        )


class Imij(models.Model):

    imagefile = models.ImageField("file", upload_to="pyusiteimages")
    name = models.CharField(
        "name",
        max_length=20,
        unique=True,
        help_text="The name to be used by authors to identify the image",
    )
    alt_text = models.TextField(
        "alt text",
        help_text="The default alt-text to be redered in the template.  This is the text displayed for the visually impaired",
    )
    title = models.CharField(
        "title",
        max_length=80,
        blank=True,
        help_text="The default title of the image to be used in rendering.  This is a tool-tip that appears when the user holds the mouse pointer over the image",
    )

    @property
    def markdown_code(self):
        return "![{}]({})".format(self.alt_text, self.imagefile.url)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(
        "title", max_length=200, help_text="The title of the article."
    )
    show_title = models.BooleanField(
        "show title",
        default=True,
        help_text="If the title should be shown (if not blank)",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="pyusite_article",
    )
    slug = models.SlugField(
        "name/slug",
        max_length=100,
        unique=True,
        help_text="The name or slug for use in URLs and within the application.  Note: Auto-generated value may not be unique. Uniquness and format are checked after submit",
    )
    iframe_document = models.ForeignKey(
        Document,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="If selected, the document to be displayed in the iframe.  This will take precedence over anything entered in the iframe source field",
    )
    iframe_src = models.CharField(
        "iframe source",
        max_length=255,
        blank=True,
        help_text="If an iframe is to be displayed, the URL of an approved iframe source (must be listed in settings), optionally followed by a css height value",
    )
    iframe_height = models.CharField(
        "iframe height",
        max_length=20,
        blank=True,
        help_text="The height of the iframe using css height syntax.  Blank to use values set in stylesheets",
    )
    content = models.TextField(
        "content",
        blank=True,
        help_text="The content of the article",
    )
    content_classes = models.CharField(
        "content classes",
        max_length=50,
        blank=True,
        help_text="Extra classes to be applied to the content when displayed",
    )
    summary = models.TextField(
        "summary",
        blank=True,
        help_text="A summary of the content of the article",
    )
    if_summary_blank = models.IntegerField(
        "If summary is blank",
        choices=[
            (0, "Show Blank"),
            (1, "Show Content"),

templates/pyusite/edit/_app_menu.html
<div class="menu app-menu">

  {% if perms.pyusite.view_article %}
    {% if 'article-' in request.resolver_match.url_name %}
      <div class="menu-article menu-here">
        Articles
      </div>
    {% else %}
      <div class="menu-article">
        <a href="{% url 'pyusite:article-list' %}">Articles</a>
      </div>
    {% endif %}
  {% endif %}


  {% if perms.pyusite.view_rack %}
    {% if 'rack-' in request.resolver_match.url_name %}
      <div class="menu-rack menu-here">
        <a href="{% url 'pyusite:rack-list' %}">Racks</a>
      </div>
    {% else %}
      <div class="menu-rack">
        <a href="{% url 'pyusite:rack-list' %}">Racks</a>
      </div>
    {% endif %}
  {% endif %}


  {% if perms.pyusite.view_section %}
    {% if 'section-' in request.resolver_match.url_name %}
      <div class="menu-section menu-here">
        Sections
      </div>
    {% else %}
      <div class="menu-section">
        <a href="{% url 'pyusite:section-list' %}">Sections</a>
      </div>
    {% endif %}
  {% endif %}



  {% if perms.pyusite.view_page %}
    {% if 'page-' in request.resolver_match.url_name %}
      <div class="menu-page menu-here">
        Pages
      </div>
    {% else %}
      <div class="menu-page">
        <a href="{% url 'pyusite:page-list' %}">Pages</a>
      </div>
    {% endif %}
  {% endif %}



  {% if user.is_authenticated %}
    <div class="menu-article">
      <form class="menu-item" method="POST" action="{% url 'logout' %}">{% csrf_token %}<button type="submit" class="menu-item" style="background:none; border:none; padding:0;">Log Out</button></form>
    </div>
  {% else %}
    <div class="menu-article">
      <a href="{% url 'login' %}?next={{ request.path }}">Log in</a>
    </div>
  {% endif %}

</div>

templates/pyusite/edit/article_confirm_delete.html
{% extends './_base.html' %}

{% block content %}
  {% include './article_menu.html' %}
  <h2>{{ object }}</h2>
  {% include './article_detail_include.html' %}
  {% include './article_menu.html' %}

{% endblock %}

templates/pyusite/edit/article_create.html
{% extends './_form.html' %}

{% block content %}
  {% include './article_menu.html' %}
  <div id="content">
  <h2>Article</h2>
  {% include './article_form.html' %}
  </div>
  {% include './article_menu.html' %}
{% endblock %}

templates/pyusite/edit/article_menu.html
<div class="menu app-menu">

  <div class="menu object-menu">

    {% if perms.view_article %}
      {% if 'article-list' == request.resolver_match.url_name %}
        <div class="menu-article menu-list menu-here">
            List
        </div>
      {% else %}
        <div class="menu-article menu-list">
          <a href="{% url 'pyusite:article-list' %}">List</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.view_article %}
      {% if 'article-detail' == request.resolver_match.url_name %}
        <div class="menu-article menu-detail menu-here">
            View
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-detail">
          <a href="{% url 'pyusite:article-detail' object.pk %}">View</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.add_article %}
      {% if 'article-create' == request.resolver_match.url_name %}
        <div class="menu-article menu-here menu-create">
          <button form="form_article" class="menu-item" type="submit" >Submit</button></form>
        </div>
      {% else %}
        <div class="menu-article menu-create">
          <a href="{% url 'pyusite:article-create' %}">Add</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.change_article %}
      {% if 'article-update' == request.resolver_match.url_name %}
        <div class="menu-article menu-update menu-here">
          <button type="submit" form="form_article" class="menu-item menu-here" >Submit Changes</button>
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-update">
          <a href="{% url 'pyusite:article-update' object.pk %}">Edit</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.delete_article %}
      {% if 'article-delete' == request.resolver_match.url_name %}
        <div class="menu-article menu-delete menu-here">
          <form method="POST" action="{% url 'pyusite:article-delete' object.pk %}">
            {% csrf_token %}
            <button type="submit" class="menu-item" >Confirm Delete</button>
          </form>
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-delete">
          <a href="{% url 'pyusite:article-delete' object.pk %}">Delete</a>
        </div>
      {% endif %}
    {% endif %}


  </div>


</div>

templates/pyusite/edit/article_update.html
{% extends './_form.html' %}


{% block content %}
  {% include './article_menu.html' %}
  <h2>{{ object }}</h2>
  {% include './article_form.html' %}
  {% include './article_menu.html' %}
{% endblock %}

templates/pyusite/edit/page_list.html
{% extends './_base.html' %}
{% load static %}
{% block content %}
{% include './page_menu.html' %}
<h2>Pages</h2>

<div class="list">
  <div class="row rowhead">
    {% include 'touglates/list_head.html' with field="" %}
    {% if 'is_home' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field="Home" %}
    {% endif %}
    {% if 'slug' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field="Slug" %}
    {% endif %}
    {% if 'title' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field="Title" %}
    {% endif %}
    {% if 'display' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field="Display" %}
    {% endif %}

  </div>

  {% for object in object_list %}
    <div class="row">
      <div class="list-field field column">
        <div><a href="{% url 'pyusite:page-detail' object.pk %}">view</a></div>
        {% if perms.change_page %}<div><a href="{% url 'pyusite:rack-update' object.pk %}">edit</a></div>{% endif %}
      </div>
      {% if 'is_home' in show_columns or not show_columns %}
        {% include 'touglates/list_field.html' with field=object.is_home %}
      {% endif %}
      {% if 'slug' in show_columns or not show_columns %}
        {% include 'touglates/list_field.html' with field=object.slug %}
      {% endif %}
      {% if 'title' in show_columns or not show_columns %}
        {% include 'touglates/list_field.html' with field=object.title %}
      {% endif %}
      {% if 'display' in show_columns or not show_columns %}
        {% include 'touglates/list_field.html' with field=object.display %}
      {% endif %}

    </div>
  {% endfor %}
  <div>Count: {{ count }}</div>

</div>

{% include './page_menu.html' %}
{% endblock %}
{% block bottomscript %}
  {{ block.super }}

{% endblock %}

templates/pyusite/edit/rack_detail_include.html
  <div class="detail">
    {% include 'touglates/detail_field.html' with label="Slug" field=object.slug %}
    {% include 'touglates/detail_field.html' with label="Title" field=object.title %}
    {% include 'touglates/detail_field.html' with label="Section" field=object.section %}

    <h3>Articles</h3>
    {% for hanger in object.hanger_set.all %}
      {% include 'touglates/detail_field.html' with label="Article:" field=hanger.article  %}
    {% endfor %}

  </div>

  <script>

  </script>

templates/pyusite/edit/rack_menu.html
<div class="menu app-menu">

  <div class="menu object-menu">

    {% if perms.view_rack %}
      {% if 'rack-list' == request.resolver_match.url_name %}
        <div class="menu-rack menu-list menu-here">
            List
        </div>
      {% else %}
        <div class="menu-rack menu-list">
          <a href="{% url 'pyusite:rack-list' %}">List</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.view_rack %}
      {% if 'rack-detail' == request.resolver_match.url_name %}
        <div class="menu-rack menu-detail menu-here">
            View
        </div>
      {% elif object.pk %}
        <div class="menu-rack menu-detail">
          <a href="{% url 'pyusite:rack-detail' object.pk %}">View</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.add_rack %}
      {% if 'rack-create' == request.resolver_match.url_name %}
        <div class="menu-rack menu-here menu-create">
          <button form="form_rack" class="menu-item" type="submit" >Submit</button></form>
        </div>
      {% else %}
        <div class="menu-rack menu-create">
          <a href="{% url 'pyusite:rack-create' %}">Add</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.change_rack %}
      {% if 'rack-update' == request.resolver_match.url_name %}
        <div class="menu-rack menu-update menu-here">
          <button type="submit" form="form_rack" class="menu-item menu-here" >Submit Changes</button>
        </div>
      {% elif object.pk %}
        <div class="menu-rack menu-update">
          <a href="{% url 'pyusite:rack-update' object.pk %}">Edit</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.delete_rack %}
      {% if 'rack-delete' == request.resolver_match.url_name %}
        <div class="menu-rack menu-delete menu-here">
          <form method="POST" action="{% url 'pyusite:rack-delete' object.pk %}">
            {% csrf_token %}
            <button type="submit" class="menu-item" >Confirm Delete</button>
          </form>
        </div>
      {% elif object.pk %}
        <div class="menu-rack menu-delete">
          <a href="{% url 'pyusite:rack-delete' object.pk %}">Delete</a>
        </div>
      {% endif %}
    {% endif %}


  </div>


</div>

templates/pyusite/edit/section_confirm_delete.html
{% extends './_delete.html' %}

{% block content %}
  {% include './section_menu.html' %}
  <h2>Delete Section: {{ object }}</h2>
  {% include './section_detail_include.html' %}
  {% include './section_menu.html' %}

{% endblock %}

templates/pyusite/edit/section_create.html
{% extends './_form.html' %}


{% block content %}
  {% include './section_menu.html' %}
  <h2>Section</h2>
  {% include './section_form.html' %}
  {% include './section_menu.html' %}
{% endblock %}

templates/pyusite/edit/section_detail.html
{% extends './_base.html' %}

{% block content %}
  {% include './section_menu.html' %}
  <h2>{{ object }}</h2>
  {% include './section_detail_include.html' %}
  {% include './section_menu.html' %}

{% endblock %}

templates/pyusite/edit/section_form.html
  <div class="form">
    {{ form.errors }}
    <form id="form_rack" method="POST">
    {% csrf_token %}
    {% include 'touglates/form_field.html' with field=form.title %}
    {% include 'touglates/form_field.html' with field=form.slug %}
    {% include 'touglates/form_field.html' with field=form.show_title %}
    {% include 'touglates/form_field.html' with field=form.page %}
    {% include 'touglates/form_field.html' with field=form.order %}
    {% include 'touglates/form_field.html' with field=form.content_before_racks %}
    {% include 'touglates/form_field.html' with field=form.content_after_racks %}
    {% include 'touglates/form_field.html' with field=form.display %}
    {% include 'touglates/form_field.html' with field=form.collapse %}
    {% include 'touglates/form_field.html' with field=form.is_special %}


    <h3>Racks</h3>

    {{ racks.management_form }}
    {% if racks.errors %}{{ racks.errors }}{% endif %}
    {% for rackform in racks.forms %}
      {% if rackform.errors %}{{ rackform.errors }}{% endif %}
      {% if rackform.id.value  %}
        <div id="div_rackform_{{ rackform.id.value }}" class="rackformsetform formsetform"  >
          {% for hiddenfield in rackform.hidden_fields %}
            {{ hiddenfield }}
          {% endfor %}
          {% include 'touglates/form_field.html' with field=rackform.title %}
          {% include 'touglates/form_field.html' with field=rackform.show_title %}
          {% include 'touglates/form_field.html' with field=rackform.slug %}
          {% include 'touglates/form_field.html' with field=rackform.width %}
          {% include 'touglates/form_field.html' with field=rackform.show_article_meta %}
          {% include 'touglates/form_field.html' with field=rackform.content_before_articles %}
          {% include 'touglates/form_field.html' with field=rackform.content_after_articles %}
          {% include 'touglates/form_field.html' with field=rackform.order %}
          {% include 'touglates/form_field.html' with field=rackform.display %}
          {% include 'touglates/form_field.html' with field=rackform.DELETE %}
        </div>
      {% else %}
        <div class="rackformsetform racknewform formsetform formsetnewform" >
          {% for hiddenfield in rackform.hidden_fields %}
            {{ hiddenfield }}
          {% endfor %}
          {% include 'touglates/form_field.html' with field=rackform.title %}
          {% include 'touglates/form_field.html' with field=rackform.show_title %}
          {% include 'touglates/form_field.html' with field=rackform.slug %}
          {% include 'touglates/form_field.html' with field=rackform.width %}
          {% include 'touglates/form_field.html' with field=rackform.show_article_meta %}
          {% include 'touglates/form_field.html' with field=rackform.content_before_articles %}
          {% include 'touglates/form_field.html' with field=rackform.content_after_articles %}
          {% include 'touglates/form_field.html' with field=rackform.order %}
          {% include 'touglates/form_field.html' with field=rackform.display %}
          {% include 'touglates/form_field.html' with field=rackform.DELETE %}
        </div>
      {% endif %}
    {% endfor %}
    <table>
      <tr>
        <td><button type="button" id="button_addrack" data-newform="racknewform">Add</button></td><td span="*"></td>
      </tr>
      {% for rack in object.rack_set.all %}
        <tr id="tr_rack_{{ rack.id }}">
          <td><button type="button" id="button_editrack_{{ rack.id }}" data-formid="div_rackform_{{ rack.id }}" data-displayid="tr_rack_{{ rack.id }}" class="rack_edit_button">edit</button></td><td>Rack: </td><td>{{ rack.title }}</td>
        </tr>
      {% endfor %}
    </table>

    <button type="Submit">Submit</button>
    </form>
  </div>

  <script>
    activateFormsetButtons(["rack"])
  </script>

templates/pyusite/edit/section_list.html
{% extends './_base.html' %}
{% load static %}
{% block content %}
{% include './section_menu.html' %}
<h2>Sections</h2>

<div class="list">
  <div class="row rowhead">

    {% include 'touglates/list_head.html' with field="-" %}

    {% if 'slug' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.slug %}
    {% endif %}
    {% if 'title' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.title %}
    {% endif %}
    {% if 'page' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.page %}
    {% endif %}
    {% if 'show_title' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.show_title %}
    {% endif %}
    {% if 'content_before_racks' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.content_before_racks %}
    {% endif %}
    {% if 'content_after_racks' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.content_after_racks %}
    {% endif %}
    {% if 'order' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.order %}
    {% endif %}
    {% if 'display' in show_columns or not show_columns %}
      {% include 'touglates/list_head.html' with field=object_labels.display %}
    {% endif %}

  </div>

      {% for object in object_list %}
        <div class="row">
          <div class="list-field field column"><a href="{% url 'pyusite:section-detail' object.pk %}">view</a></div>
          {% if 'slug' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.slug %}
          {% endif %}
          {% if 'title' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.title %}
          {% endif %}
          {% if 'page' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.page %}
          {% endif %}
          {% if 'show_title' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.show_title %}
          {% endif %}
          {% if 'content_before_objects' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.content_before_objects %}
          {% endif %}
          {% if 'content_after_objects' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.content_after_objects %}
          {% endif %}
          {% if 'order' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.order %}
          {% endif %}
          {% if 'display' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=object.display %}
          {% endif %}

        </div>
      {% endfor %}
      <div>Count: {{ count }}</div>

    </div>
  </div>

{% include './section_menu.html' %}
{% endblock %}
{% block bottomscript %}
  {{ block.super }}

{% endblock %}